[package]
name = "wsf"
version = "0.1.7"
authors = ["Brian McCallister <brianm@skife.org>"]
license = "Apache-2.0"
build = "build.rs"
edition = "2018"

[dependencies]
hyper = "0.10"
rustc-serialize = "0.3"
chrono = "0.2"
regex = "0.1"
log = "0.3"
env_logger = "0.6"
docopt = "1.0.2"
dirs = "1.0.4"
serde = "1.0.89"
serde_derive = "1.0.89"
failure_derive = "0.1.5"
failure = "0.1.5"

[dev-dependencies]
mockito = "0.16.0"
pretty_assertions = "0.6.1"