[package]
name = "wsf"
version = "1.1.9"
authors = ["Brian McCallister <brianm@skife.org>"]
license = "Apache-2.0"
build = "build.rs"
edition = "2018"
documentation = "https://github.com/brianm/wsf"

[dependencies]
chrono = "0.2"
dirs = "1.0"
docopt = "1.1"
env_logger = "0.6"
exitfailure = "0.5"
failure = "0.1"
failure_derive = "0.1"
human-panic = "1.0"
lazy_static = "1.3.0"
log = "0.4"
regex = "1.1"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
mockito = "0.16"
pretty_assertions = "0.6"
