[package]
name = "wsf"
version = "0.1.0"
authors = ["Brian McCallister <brianm@skife.org>"]

[dependencies]
hyper = "0.6.1"
rustc-serialize = "0.3.15"
chrono = "0.2.15"
regex = "0.1.40"
log = "0.3.1"
env_logger = "0.3.1"
docopt = "0.6.70"
