[package]
name = "wsf"
version = "1.1.9"
authors = ["Brian McCallister <brianm@skife.org>"]
license = "Apache-2.0"
build = "build.rs"
edition = "2018"
documentation = "https://github.com/brianm/wsf"

[dependencies]
reqwest = "0.9"
chrono = "0.2"
regex = "0.1"
log = "0.3"
env_logger = "0.6"
docopt = "1.0"
dirs = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure_derive = "0.1"
failure = "0.1"
human-panic = "1.0"
exitfailure = "0.5"

[dev-dependencies]
mockito = "0.16"
pretty_assertions = "0.6"
