[package]
name = "wsf"
version = "1.1.9"
authors = ["Brian McCallister <brianm@skife.org>"]
license = "Apache-2.0"
build = "build.rs"
edition = "2018"
documentation = "https://github.com/brianm/wsf"

[dependencies]
chrono = "0.4"
dirs = "1"
docopt = "1"
env_logger = "0.6"
human-panic = "1"
lazy_static = "1"
log = "0.4"
regex = "1"
reqwest = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
anyhow = "1"
thiserror = "1"

[dev-dependencies]
mockito = "0.16"
pretty_assertions = "0.6"

[profile.release]
lto = true
