[package]
name = "wsf"
version = "0.1.6"
authors = ["Brian McCallister <brianm@skife.org>"]
build = "build.rs"

[dependencies]
hyper = "0.10"
rustc-serialize = "0.3"
chrono = "0.2"
regex = "0.1"
log = "0.3"
env_logger = "0.3"
docopt = "0.6"
